apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nwe37p0dp-dotnet-basic
  janus-idp.io/tekton: nwe37p0dp-dotnet-basic
  backstage.io/kubernetes-id: nwe37p0dp-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nwe37p0dp-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
